const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');

test('programlar ekranında güncel hoca ve video kütüphanesi yüklenir',()=>{
  const html=read('index.html'),js=read('program-videos-v1.js'),css=read('program-videos-v1.css');
  assert.match(html,/program-videos-v1\.css\?v=1\.3\.0/);
  assert.match(html,/program-videos-v1\.js\?v=1\.7\.0/);
  assert.match(js,/HOCALAR &amp; VİDEOLAR/);
  assert.match(js,/data-scope="TYT"/);
  assert.match(js,/data-scope="AYT"/);
  assert.match(js,/teachers-v2-feed\.json/);
  assert.match(js,/archiveIndex/);
  assert.match(js,/data-playlist-view/);
  assert.match(js,/renderPlaylistDetail/);
  assert.match(js,/contentComplete/);
  assert.match(js,/playlists/);
  assert.match(js,/konu anlatımı/);
  assert.match(js,/programMainEmpty/);
  assert.match(js,/deneme çözümü/);
  assert.match(js,/programTaskVideo/);
  assert.match(js,/programCustomTab/);
  assert.match(js,/Programa ekle/);
  assert.match(js,/Biosem/);
  assert.match(js,/Senin Biyolojin/);
  assert.match(js,/MEDIA_REPO_PATH/);
  assert.match(js,/teacherMedia\(feed,state\.teacher\)/);
  assert.match(js,/loadArchive\(media,force\)/);
  assert.doesNotMatch(js,/function subjectRelevant/);
  assert.doesNotMatch(js,/function teacherRelevant/);
  assert.match(js,/function subjectMatches/);
  assert.match(js,/if\(state\.scope==="AYT"\)/);
  assert.match(js,/const tytOrNeutral=checked\.filter\(row=>!row\.match\?\.ayt\)/);
  assert.match(js,/Promise\.all\(missing\.map\(index=>loadArchivePage/);
  assert.match(js,/state\.hasMore=false/);
  assert.doesNotMatch(js,/return scoped\.length\?scoped/);
  assert.match(css,/\.coach-video-library/);
  assert.match(css,/\.coach-playlist-detail-head/);
});
